POST http://localhost:8080/api/login
Content-Type: application/json

{
  "employeeNo" : "BA0120",
  "password" : "1111"
}

###
GET http://localhost:8080/api/userinfo/me
Accept: application/json

###
### GET request to example server

PUT http://localhost:8080/api/userinfo/me
Content-Type: application/json

{
  "email" : "new@example.com",
  "phone" : "010-9999-8888"

}

###